apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml: [./infra/k8s/*]
deploy:
  kubeContext: minikube
build:
  local:
    push: false
  artifacts:
    - image: chaitanya31/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: chaitanya31/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: chaitanya31/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: chaitanya31/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
